//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "invoice_items"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub invoice_id: Option<i64>,
    pub name: Option<String>,
    pub unit_price: Option<Decimal>,
    pub vat_rate: Option<Decimal>,
    pub quantity: Option<i32>,
    pub value: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    InvoiceId,
    Name,
    UnitPrice,
    VatRate,
    Quantity,
    Value,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::InvoiceId => ColumnType::BigInteger.def().null(),
            Self::Name => ColumnType::String(None).def().null(),
            Self::UnitPrice => ColumnType::Decimal(Some((8u32, 2u32))).def().null(),
            Self::VatRate => ColumnType::Decimal(Some((4u32, 1u32))).def().null(),
            Self::Quantity => ColumnType::Integer.def().null(),
            Self::Value => ColumnType::Decimal(Some((8u32, 2u32))).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
