//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Copy , Clone , Default , Debug , DeriveEntity)] pub struct Entity ;

impl EntityName for Entity { fn table_name (& self) -> & str { "clients" } }

# [derive (Clone , Debug , PartialEq , DeriveModel , DeriveActiveModel , Serialize , Deserialize)] pub struct Model { pub id : i64 , pub uid : Option < Uuid > , pub name : Option < String > , pub created_at : DateTimeUtc , pub updated_at : DateTimeUtc , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveColumn)] pub enum Column { Id , Uid , Name , CreatedAt , UpdatedAt , }

# [derive (Copy , Clone , Debug , EnumIter , DerivePrimaryKey)] pub enum PrimaryKey { Id , }

impl PrimaryKeyTrait for PrimaryKey { type ValueType = i64 ; fn auto_increment () -> bool { true } }

# [derive (Copy , Clone , Debug , EnumIter)] pub enum Relation { }

impl ColumnTrait for Column { type EntityName = Entity ; fn def (& self) -> ColumnDef { match self { Self :: Id => ColumnType :: BigInteger . def () , Self :: Uid => ColumnType :: Uuid . def () . null () , Self :: Name => ColumnType :: String (None) . def () . null () , Self :: CreatedAt => ColumnType :: Timestamp . def () , Self :: UpdatedAt => ColumnType :: Timestamp . def () , } } }

impl RelationTrait for Relation { fn def (& self) -> RelationDef { panic ! ("No RelationDef") } }

impl ActiveModelBehavior for ActiveModel { }