//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Copy , Clone , Default , Debug , DeriveEntity)] pub struct Entity ;

impl EntityName for Entity { fn table_name (& self) -> & str { "event_store_events_in_streams" } }

# [derive (Clone , Debug , PartialEq , DeriveModel , DeriveActiveModel , Serialize , Deserialize)] pub struct Model { pub id : i32 , pub stream : String , pub position : Option < i32 > , pub event_id : Uuid , pub created_at : DateTimeUtc , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveColumn)] pub enum Column { Id , Stream , Position , EventId , CreatedAt , }

# [derive (Copy , Clone , Debug , EnumIter , DerivePrimaryKey)] pub enum PrimaryKey { Id , }

impl PrimaryKeyTrait for PrimaryKey { type ValueType = i32 ; fn auto_increment () -> bool { true } }

# [derive (Copy , Clone , Debug , EnumIter)] pub enum Relation { }

impl ColumnTrait for Column { type EntityName = Entity ; fn def (& self) -> ColumnDef { match self { Self :: Id => ColumnType :: Integer . def () , Self :: Stream => ColumnType :: String (None) . def () , Self :: Position => ColumnType :: Integer . def () . null () , Self :: EventId => ColumnType :: Uuid . def () , Self :: CreatedAt => ColumnType :: Timestamp . def () , } } }

impl RelationTrait for Relation { fn def (& self) -> RelationDef { panic ! ("No RelationDef") } }

impl ActiveModelBehavior for ActiveModel { }