//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub mod prelude;

pub mod ar_internal_metadata;
pub mod client_orders;
pub mod clients;
pub mod customers;
pub mod event_store_events;
pub mod event_store_events_in_streams;
pub mod invoice_items;
pub mod invoices;
pub mod invoices_orders;
pub mod order_lines;
pub mod orders;
pub mod orders_customers;
pub mod orders_products;
pub mod products;
pub mod refinery_schema_history;
pub mod schema_migrations;
pub mod shipments;
pub mod shipments_orders;
