//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "orders"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub uid: Uuid,
    pub number: Option<String>,
    pub customer: Option<String>,
    pub state: Option<String>,
    pub percentage_discount: Option<Decimal>,
    pub total_value: Option<Decimal>,
    pub discounted_value: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uid,
    Number,
    Customer,
    State,
    PercentageDiscount,
    TotalValue,
    DiscountedValue,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::Uid => ColumnType::Uuid.def(),
            Self::Number => ColumnType::String(None).def().null(),
            Self::Customer => ColumnType::String(None).def().null(),
            Self::State => ColumnType::String(None).def().null(),
            Self::PercentageDiscount => ColumnType::Decimal(Some((8u32, 2u32))).def().null(),
            Self::TotalValue => ColumnType::Decimal(Some((8u32, 2u32))).def().null(),
            Self::DiscountedValue => ColumnType::Decimal(Some((8u32, 2u32))).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
