[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
entities = { path = "../entities" }
sea-orm-migration = "^0.8.0"
