[package]
name = "cqrs03"
version = "0.1.0"
rust_version = "1.56.0"
edition = "2021"

[workspace]
members = ["entities",
 "migrations",
 "rtm"]

[dependencies]
rtm = "0"
refinery = { version = "0.8", features = ["postgres"]}
